site_name: CloudLab Terraform Provider
site_description: Documentation for automating CloudLab experiments with Terraform
repo_url: https://github.com/CSC478-WCU/terraform-provider-cloudlab
repo_name: CSC478-WCU/terraform-provider-cloudlab
edit_uri: edit/docs/docs/


theme:
  name: material
  logo: assets/images/cloudlab-flask.png
  features:
    - navigation.instant
    - navigation.expand
    - navigation.tracking
    - content.code.copy
    - header.autohide
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


nav:
  - Home: index.md
  - Overview:
      - Introduction: overview/introduction.md
      - What Is CloudLab: overview/cloudlab.md
      - Why Terraform: overview/why-terraform.md
  - Usage Guides:
      - Getting Started: usage/getting-started.md
      - Authentication (PEM): usage/auth.md
      - Terraform Basics: usage/what-is-terraform.md
      - Usage Guide: usage/usage.md
      - CI/CD With Github Actions: usage/github-actions.md
  - How It Works:
      - Provider Architecture: internals/architecture.md
  - License: license.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - assets/css/overrides.css

extra:
  copyright: Tyler Geiger — West Chester University · Educational and research use. Not affiliated with the official CloudLab team.
